<a href="https://colab.research.google.com/github/srk310590/First_nlp/blob/master/Disaster_Identifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
from sklearn import feature_extraction, linear_model, model_selection, preprocessing

Code to upload a file from drive

In [0]:
from google.colab import files
uploaded = files.upload()

In [0]:
import io

In [0]:
train_df = pd.read_csv(io.BytesIO(uploaded['Filename.csv']))
# Dataset is now stored in a Pandas Dataframe

KeyError: ignored

In [0]:
url1 = "https://raw.githubusercontent.com/srk310590/First_nlp/master/train.csv"
url2 = "https://raw.githubusercontent.com/srk310590/First_nlp/master/test.csv"

In [0]:
train_df = pd.read_csv(url1) 

In [6]:
train_df

id keyword  ...                                               text target
0         1     NaN  ...  Our Deeds are the Reason of this #earthquake M...      1
1         4     NaN  ...             Forest fire near La Ronge Sask. Canada      1
2         5     NaN  ...  All residents asked to 'shelter in place' are ...      1
3         6     NaN  ...  13,000 people receive #wildfires evacuation or...      1
4         7     NaN  ...  Just got sent this photo from Ruby #Alaska as ...      1
...     ...     ...  ...                                                ...    ...
7608  10869     NaN  ...  Two giant cranes holding a bridge collapse int...      1
7609  10870     NaN  ...  @aria_ahrary @TheTawniest The out of control w...      1
7610  10871     NaN  ...  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...      1
7611  10872     NaN  ...  Police investigating after an e-bike collided ...      1
7612  10873     NaN  ...  The Latest: More Homes Razed by Northern Calif...      1

[7613 rows x 5 columns]

In [0]:
test_df = pd.read_csv(url2)

In [0]:
train1 = train_df['text'].str.replace('[^A-Za-z\s]+', '')
test1  = test_df['text'].str.replace('[^A-Za-z\s]+', '')

In [0]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 

In [0]:
train2 = train1.str.lower()
test2  = test1.str.lower()

In [0]:
import nltk

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
stop = stopwords.words('english')

In [0]:
train3 = train2.apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
vec = CountVectorizer()
X = vec.fit_transform(train3)
df = pd.DataFrame(X.toarray(), columns=vec.get_feature_names())
print(df)

      aa  aaaa  aaaaaaallll  aaaaaand  ...  zumiez  zurich  zxathetis  zzzz
0      0     0            0         0  ...       0       0          0     0
1      0     0            0         0  ...       0       0          0     0
2      0     0            0         0  ...       0       0          0     0
3      0     0            0         0  ...       0       0          0     0
4      0     0            0         0  ...       0       0          0     0
...   ..   ...          ...       ...  ...     ...     ...        ...   ...
7608   0     0            0         0  ...       0       0          0     0
7609   0     0            0         0  ...       0       0          0     0
7610   0     0            0         0  ...       0       0          0     0
7611   0     0            0         0  ...       0       0          0     0
7612   0     0            0         0  ...       0       0          0     0

[7613 rows x 21339 columns]


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(df, train_df['target'], test_size=0.2, random_state=42)

In [19]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(6090, 21339)
(1523, 21339)
(6090,)
(1523,)


In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
clf = RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)

In [0]:
model = clf.fit(X_train, y_train)

In [23]:
# Make predictions
preds = model.predict(X_test)
print(preds)

[0 0 0 ... 1 1 0]


In [0]:
from sklearn.metrics import accuracy_score

In [25]:
# Evaluate accuracy
print(accuracy_score(y_test, preds))

0.7800393959290873


In [0]:
from sklearn.metrics import f1_score

In [27]:
f1_score(y_test, preds, zero_division=1)

0.7058823529411765

### Predict for Test tweets

In [0]:
test3 = test2.apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [29]:
test3

0                             happened terrible car crash
1       heard earthquake different cities stay safe ev...
2       forest fire spot pond geese fleeing across str...
3                   apocalypse lighting spokane wildfires
4                     typhoon soudelor kills china taiwan
                              ...                        
3258    earthquake safety los angeles safety fasteners...
3259    storm ri worse last hurricane cityampothers ha...
3260      green line derailment chicago httptcoutbxlcbiuy
3261    meg issues hazardous weather outlook hwo httpt...
3262    cityofcalgary activated municipal emergency pl...
Name: text, Length: 3263, dtype: object

In [0]:
temp = vec.transform(test3)

In [0]:
temp1 = temp.toarray()

In [45]:
len(temp1[1])

11977

In [47]:
vec.transform(test3)

<3263x21339 sparse matrix of type '<class 'numpy.int64'>'
	with 24579 stored elements in Compressed Sparse Row format>

In [30]:
Y = vec.transform(test3)
df_test = pd.DataFrame(Y.toarray(), columns=vec.get_feature_names())
print(df_test)

      aa  aaaa  aaaaaaallll  aaaaaand  ...  zumiez  zurich  zxathetis  zzzz
0      0     0            0         0  ...       0       0          0     0
1      0     0            0         0  ...       0       0          0     0
2      0     0            0         0  ...       0       0          0     0
3      0     0            0         0  ...       0       0          0     0
4      0     0            0         0  ...       0       0          0     0
...   ..   ...          ...       ...  ...     ...     ...        ...   ...
3258   0     0            0         0  ...       0       0          0     0
3259   0     0            0         0  ...       0       0          0     0
3260   0     0            0         0  ...       0       0          0     0
3261   0     0            0         0  ...       0       0          0     0
3262   0     0            0         0  ...       0       0          0     0

[3263 rows x 21339 columns]


In [31]:
preds_test = model.predict(df_test)
print(preds_test)

[0 1 1 ... 1 1 1]


In [0]:
temp  = pd.DataFrame([test_df['id'],preds_test])

In [53]:
type(preds_test)

numpy.ndarray

In [32]:
test_df['id']

0           0
1           2
2           3
3           9
4          11
        ...  
3258    10861
3259    10865
3260    10868
3261    10874
3262    10875
Name: id, Length: 3263, dtype: int64

In [33]:
preds_test

array([0, 1, 1, ..., 1, 1, 1])

In [34]:
pd.concat([test_df['id'],preds_test], axis=1)

TypeError: ignored

In [37]:
np.transpose(preds_test)

array([0, 1, 1, ..., 1, 1, 1])

In [0]:
results  = np.transpose(temp)

In [48]:
results.to_csv("C:/Kaggle/NLP - Disaster or not/submission1.csv")

FileNotFoundError: ignored

In [0]:
from google.colab import files

In [0]:
results.to_csv('submission1.csv') 
files.download('submission1.csv')